version: 2
updates:
- package-ecosystem: npm
  directory: "/gatsby-theme-sputnik"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby
    versions:
    - 3.0.4
    - 3.1.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.0.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.0.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.0.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.0.0
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
